// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID        int32
	Service   string
	Level     string
	Message   string
	CreatedAt pgtype.Timestamp
}
