// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (
  service, level, message
) VALUES ( $1, $2, $3 ) RETURNING id, service, level, message, created_at
`

type CreateLogParams struct {
	Service string
	Level   string
	Message string
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, createLog, arg.Service, arg.Level, arg.Message)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Level,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many
SELECT id, service, level, message, created_at FROM logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListLogs(ctx context.Context, limit int32) ([]Log, error) {
	rows, err := q.db.Query(ctx, listLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
